### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Julien-Broyard/jikants#11]
Hi @Julien-Broyard  Tobaloidee again.. :) want a logo for this project? 😊

**Comment by Julien-Broyard** [comment]
Hey, it could be nice indeed !

**Comment by Tobaloidee** [comment]
can you tell me something about this project? What its function? 😃

**Comment by Julien-Broyard** [comment]
It is an API wrapper for the Jikan REST API ! (An unofficial MyAnimeList API)

**Comment by Tobaloidee** [comment]
Thank you for the feedback! Will start brainstorming..I will just post the initial design here when done..😀👍

**Comment by Julien-Broyard** [comment]
Thanks a lot !

**Comment by Tobaloidee** [comment]
Here's what I came up with @Julien-Broyard 

-modern and meaningful design 

![jikants-02](https://user-images.githubusercontent.com/36028424/56847131-e5a61600-6909-11e9-9cd4-75b6d101b1a2.png)

will make a PR once its ok with you 😊

**Comment by Julien-Broyard** [comment]
Wow it looks awesome as always :smile:

**Comment by Tobaloidee** [comment]
Which main color do you prefer? the Red or Blue?

**Comment by Julien-Broyard** [comment]
The blue one

**Comment by Tobaloidee** [comment]
copy that! will make a PR after I finalize it

**Comment by Julien-Broyard** [comment]
:ok_hand:

**Comment by Tobaloidee** [comment]
Here's the PR #12 with the logo upload & readme update.. You can download all the versions and formats of the new logo [HERE](https://drive.google.com/drive/u/1/folders/1wBtyGNxo2nnVAp0nRNva_H-qp2VdRq4e) @Julien-Broyard  

Thanks so much again for accepting my contribution!! Goodluck to the project! I am just a mention away if you need any help with logos. 👍😊

**Comment by Julien-Broyard** [comment]
Thanks again !
