### ISSUE TITLE
[BUG] FSHARP offline website

### ISSUE THREAD

**Issue by absolute-code** [Julien-Broyard/jikants#35]
Why https://fsharpcommunity.netlify.com/ is offline ? :( (Sorry it's off topic but it intrigues me)

**Comment by Julien-Broyard** [comment]
It is offline since I might redo it for the same language or another one later on.

**Comment by absolute-code** [comment]
Could you put it back online for F# apprenticeship with what you had already done, please?

**Comment by Julien-Broyard** [comment]
I'll think about that.

**Comment by absolute-code** [comment]
Thank you, I would like to put it online in the evening if possible 
I know some people who are interested in learning F# but who are struggling

**Comment by absolute-code** [comment]
News ? @Julien-Broyard
