### ISSUE TITLE
[FEATURE] Fsharp Website

### ISSUE THREAD

**Issue by absolute-code** [Julien-Broyard/jikants#38]
I reopen a ticket because I am waiting for an answer for issue #35

**Comment by Julien-Broyard** [comment]
I've searched for the files nevertheless I've realized that I deleted them since I was planning on making another one when I'll have time. So to answer you I no longer have the website.

**Comment by absolute-code** [comment]
Okay, and why did you leave the discord? 
Are you planning to do another one when you no longer do F#?
